const InterestList = () => {
  const list = [
    "Cricket",
    "Football",
    "Basketball",
    "Outdoors",
    "Hiking",
    "Camping",
    "trekking",
    "Comic",
    "Manga",
    "Manhwa",
    "Manhua",
    "Hentai",
    "Movies",
    "Anime",
    "Netflix",
    "Youtube",
    "Reels",
    "TikTok",
    "Music",
    "Violin",
    "Piano",
    "Guitar",
    "Painting",
    "Sketching",
    "Coloring",
    "Blender",
    "3d artwork",
    "Animation",
    "Sound production",
    "Craft",
    "Programming",
    "C/C++",
    "Java",
    "Python",
    "Rust",
    "JavaScript",
    "TypeScript",
    "Web Development",
    "Linux",
    "Linux Gaming",
    "OpenSource",
    "Cars",
    "Bikes",
    "Biking",
    "Swimming",
    "Athletics",
    "Running",
    "Sprinting",
    "Gym",
    "Weapons",
    "UFC",
    "MMA",
    "Martial Arts",
    "Studying",
    "Physics",
    "Astrophysics",
    "QuantumPhysics",
  ];

  return list;
};

export default InterestList;
